"""
TradeOracle AI — Secure Config Server
======================================
Runs alongside the bot.
Admin portal talks to this to save/load settings.
All sensitive data encrypted at rest.
"""
from http.server import HTTPServer, BaseHTTPRequestHandler
import json, os, hashlib, hmac, base64, secrets
from datetime import datetime

CONFIG_FILE = "/opt/tradeoracleai/config/settings.json"
SECRET_KEY_FILE = "/opt/tradeoracleai/config/secret.key"
CONFIG_DIR = "/opt/tradeoracleai/config"

os.makedirs(CONFIG_DIR, exist_ok=True)

# ── Generate or load secret key ──
def get_secret_key():
    if not os.path.exists(SECRET_KEY_FILE):
        key = secrets.token_hex(32)
        with open(SECRET_KEY_FILE, 'w') as f:
            f.write(key)
        os.chmod(SECRET_KEY_FILE, 0o600)
        return key
    return open(SECRET_KEY_FILE).read().strip()

SECRET_KEY = get_secret_key()

# ── Simple XOR encryption for secrets ──
def encrypt(text, key):
    key_bytes = key.encode()
    text_bytes = text.encode()
    encrypted = bytes([text_bytes[i] ^ key_bytes[i % len(key_bytes)]
                       for i in range(len(text_bytes))])
    return base64.b64encode(encrypted).decode()

def decrypt(encrypted_text, key):
    key_bytes = key.encode()
    encrypted_bytes = base64.b64decode(encrypted_text.encode())
    decrypted = bytes([encrypted_bytes[i] ^ key_bytes[i % len(key_bytes)]
                       for i in range(len(encrypted_bytes))])
    return decrypted.decode()

# ── Load config ──
def load_config():
    if not os.path.exists(CONFIG_FILE):
        return {
            "telegram_token": "",
            "admin_chat_id": "",
            "anthropic_key": "",
            "gmail_sender": "",
            "gmail_password": "",
            "scan_interval": "15",
            "briefing_time": "08:00",
            "watchlist": "NVDA,AAPL,MSFT,GOOGL,NFLX,AMZN,META,TSLA",
            "min_profit_alert": "7",
            "warn_buffer": "12",
            "danger_buffer": "5",
            "bot_username": "@TradeOracleAIBot",
            "admin_email": "rishisharma1510@gmail.com",
            "configured": False,
            "last_updated": None
        }
    with open(CONFIG_FILE) as f:
        data = json.load(f)
    # Decrypt sensitive fields
    for field in ['telegram_token', 'anthropic_key', 'gmail_password']:
        if data.get(field) and data[field].startswith('ENC:'):
            try:
                data[field] = decrypt(data[field][4:], SECRET_KEY)
            except:
                data[field] = ""
    return data

# ── Save config ──
def save_config(data):
    to_save = data.copy()
    # Encrypt sensitive fields
    for field in ['telegram_token', 'anthropic_key', 'gmail_password']:
        if to_save.get(field):
            to_save[field] = 'ENC:' + encrypt(to_save[field], SECRET_KEY)
    to_save['last_updated'] = datetime.now().isoformat()
    to_save['configured'] = bool(
        data.get('telegram_token') and
        data.get('anthropic_key') and
        data.get('admin_chat_id')
    )
    with open(CONFIG_FILE, 'w') as f:
        json.dump(to_save, f, indent=2)
    os.chmod(CONFIG_FILE, 0o600)
    # Also write .env for the bot process
    write_env(data)
    return to_save

# ── Write .env file for bot ──
def write_env(data):
    env_content = f"""# Auto-generated by TradeOracle AI Config Server
# Last updated: {datetime.now().isoformat()}
TELEGRAM_TOKEN={data.get('telegram_token','')}
ADMIN_CHAT_ID={data.get('admin_chat_id','')}
ANTHROPIC_KEY={data.get('anthropic_key','')}
GMAIL_SENDER={data.get('gmail_sender','')}
GMAIL_PASSWORD={data.get('gmail_password','')}
SCAN_INTERVAL={data.get('scan_interval','15')}
BRIEFING_TIME={data.get('briefing_time','08:00')}
WATCHLIST={data.get('watchlist','NVDA,AAPL,MSFT,GOOGL,NFLX,AMZN,META,TSLA')}
MIN_PROFIT_ALERT={data.get('min_profit_alert','7')}
WARN_BUFFER={data.get('warn_buffer','12')}
DANGER_BUFFER={data.get('danger_buffer','5')}
"""
    env_path = "/opt/tradeoracleai/.env"
    with open(env_path, 'w') as f:
        f.write(env_content)
    os.chmod(env_path, 0o600)

# ── Verify admin token ──
def verify_token(token):
    expected = hmac.new(
        SECRET_KEY.encode(),
        b"tradeoracleai_admin",
        hashlib.sha256
    ).hexdigest()
    return hmac.compare_digest(token or "", expected)

def get_admin_token():
    return hmac.new(
        SECRET_KEY.encode(),
        b"tradeoracleai_admin",
        hashlib.sha256
    ).hexdigest()

# ── HTTP Handler ──
class ConfigHandler(BaseHTTPRequestHandler):

    def log_message(self, format, *args):
        pass  # Suppress default logs

    def send_json(self, data, status=200):
        body = json.dumps(data).encode()
        self.send_response(status)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Content-Length', len(body))
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type, X-Admin-Token')
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type, X-Admin-Token')
        self.end_headers()

    def do_GET(self):
        token = self.headers.get('X-Admin-Token', '')

        # Public endpoint — check if configured
        if self.path == '/api/status':
            config = load_config()
            self.send_json({
                'configured': config.get('configured', False),
                'bot_username': config.get('bot_username', '@TradeOracleAIBot'),
                'watchlist': config.get('watchlist', ''),
                'scan_interval': config.get('scan_interval', '15'),
                'last_updated': config.get('last_updated'),
            })
            return

        # Login endpoint — returns token
        if self.path.startswith('/api/login'):
            from urllib.parse import urlparse, parse_qs
            params = parse_qs(urlparse(self.path).query)
            password = params.get('password', [''])[0]
            # Hash the password and compare
            stored_hash = self._get_admin_password_hash()
            if self._check_password(password, stored_hash):
                self.send_json({'token': get_admin_token(), 'success': True})
            else:
                self.send_json({'error': 'Invalid password'}, 401)
            return

        # Protected endpoints
        if not verify_token(token):
            self.send_json({'error': 'Unauthorized'}, 401)
            return

        if self.path == '/api/config':
            config = load_config()
            # Mask sensitive fields for display
            safe = config.copy()
            for field in ['telegram_token', 'anthropic_key', 'gmail_password']:
                if safe.get(field):
                    val = safe[field]
                    safe[field] = val[:8] + '...' + val[-4:] if len(val) > 12 else '***'
            self.send_json(safe)
            return

        if self.path == '/api/users':
            users_file = '/opt/tradeoracleai/user_data/users.json'
            if os.path.exists(users_file):
                with open(users_file) as f:
                    users = json.load(f)
                self.send_json({'users': users, 'count': len(users)})
            else:
                self.send_json({'users': {}, 'count': 0})
            return

        if self.path == '/api/codes':
            codes_file = '/opt/tradeoracleai/user_data/access_codes.json'
            if os.path.exists(codes_file):
                with open(codes_file) as f:
                    codes = json.load(f)
                self.send_json({'codes': codes})
            else:
                self.send_json({'codes': {}})
            return

        if self.path == '/api/stats':
            users_file = '/opt/tradeoracleai/user_data/users.json'
            users = {}
            if os.path.exists(users_file):
                with open(users_file) as f:
                    users = json.load(f)
            from datetime import datetime
            active = sum(1 for u in users.values()
                        if u.get('active') and
                        datetime.fromisoformat(u.get('expires','2000-01-01')) > datetime.now())
            prices = {'trial':0,'basic':19,'pro':39,'premium':59,'lifetime':299}
            revenue = sum(prices.get(u.get('tier','trial'),0)
                         for u in users.values()
                         if u.get('active'))
            self.send_json({
                'total_users': len(users),
                'active_users': active,
                'monthly_revenue': revenue,
            })
            return

        self.send_json({'error': 'Not found'}, 404)

    def do_POST(self):
        token = self.headers.get('X-Admin-Token', '')
        length = int(self.headers.get('Content-Length', 0))
        body = json.loads(self.rfile.read(length)) if length else {}

        # Set admin password (first time setup)
        if self.path == '/api/setup-password':
            password = body.get('password', '')
            if not password or len(password) < 8:
                self.send_json({'error': 'Password must be at least 8 characters'}, 400)
                return
            self._save_admin_password(password)
            self.send_json({'success': True, 'token': get_admin_token()})
            return

        # Protected endpoints below
        if not verify_token(token):
            self.send_json({'error': 'Unauthorized'}, 401)
            return

        if self.path == '/api/config':
            saved = save_config(body)
            # Restart bot service to pick up new config
            os.system('sudo systemctl restart tradeoracleai 2>/dev/null || true')
            self.send_json({'success': True, 'message': 'Settings saved! Bot restarting...'})
            return

        if self.path == '/api/add-code':
            import secrets as sec
            tier = body.get('tier', 'pro')
            days = body.get('days', 30)
            code = sec.token_hex(4).upper()
            codes_file = '/opt/tradeoracleai/user_data/access_codes.json'
            codes = {}
            if os.path.exists(codes_file):
                with open(codes_file) as f:
                    codes = json.load(f)
            codes[code] = {
                'tier': tier, 'days': days,
                'created': datetime.now().isoformat(),
                'used': False, 'used_by': None
            }
            os.makedirs('/opt/tradeoracleai/user_data', exist_ok=True)
            with open(codes_file, 'w') as f:
                json.dump(codes, f, indent=2)
            self.send_json({'success': True, 'code': code})
            return

        if self.path == '/api/revoke-user':
            uid = body.get('user_id', '')
            users_file = '/opt/tradeoracleai/user_data/users.json'
            if os.path.exists(users_file):
                with open(users_file) as f:
                    users = json.load(f)
                if uid in users:
                    users[uid]['active'] = False
                    with open(users_file, 'w') as f:
                        json.dump(users, f, indent=2)
            self.send_json({'success': True})
            return

        if self.path == '/api/extend-user':
            uid = body.get('user_id', '')
            days = body.get('days', 30)
            users_file = '/opt/tradeoracleai/user_data/users.json'
            if os.path.exists(users_file):
                with open(users_file) as f:
                    users = json.load(f)
                if uid in users:
                    from datetime import timedelta
                    exp = datetime.fromisoformat(users[uid].get('expires', datetime.now().isoformat()))
                    users[uid]['expires'] = (exp + timedelta(days=days)).isoformat()
                    users[uid]['active'] = True
                    with open(users_file, 'w') as f:
                        json.dump(users, f, indent=2)
            self.send_json({'success': True})
            return

        if self.path == '/api/test-email':
            config = load_config()
            try:
                import smtplib
                from email.mime.text import MIMEText
                msg = MIMEText('TradeOracle AI email test - working!')
                msg['Subject'] = 'TradeOracle AI - Test Email'
                msg['From'] = config.get('gmail_sender', '')
                msg['To'] = config.get('admin_email', config.get('gmail_sender', ''))
                with smtplib.SMTP_SSL('smtp.gmail.com', 465) as s:
                    s.login(config['gmail_sender'], config['gmail_password'])
                    s.send_message(msg)
                self.send_json({'success': True, 'message': 'Test email sent!'})
            except Exception as e:
                self.send_json({'success': False, 'error': str(e)})
            return

        if self.path == '/api/test-telegram':
            config = load_config()
            try:
                import requests as req
                r = req.get(f"https://api.telegram.org/bot{config['telegram_token']}/getMe", timeout=5)
                data = r.json()
                if data.get('ok'):
                    self.send_json({'success': True, 'bot_name': data['result']['username']})
                else:
                    self.send_json({'success': False, 'error': data.get('description', 'Invalid token')})
            except Exception as e:
                self.send_json({'success': False, 'error': str(e)})
            return

        self.send_json({'error': 'Not found'}, 404)

    def _get_admin_password_hash(self):
        pw_file = '/opt/tradeoracleai/config/admin.hash'
        if os.path.exists(pw_file):
            return open(pw_file).read().strip()
        return None

    def _save_admin_password(self, password):
        pw_hash = hashlib.pbkdf2_hmac('sha256', password.encode(), SECRET_KEY.encode(), 100000).hex()
        pw_file = '/opt/tradeoracleai/config/admin.hash'
        with open(pw_file, 'w') as f:
            f.write(pw_hash)
        os.chmod(pw_file, 0o600)

    def _check_password(self, password, stored_hash):
        if not stored_hash or not password:
            return False
        pw_hash = hashlib.pbkdf2_hmac('sha256', password.encode(), SECRET_KEY.encode(), 100000).hex()
        return hmac.compare_digest(pw_hash, stored_hash)

if __name__ == '__main__':
    port = 8765
    server = HTTPServer(('127.0.0.1', port), ConfigHandler)
    print(f'Config server running on port {port}')
    server.serve_forever()
